services:
  geth:
    build: ./geth/
    volumes:
      - blockchain:/blockchain
    ports:
      - "8545:8545"
      - "7545:7545"
  web:
    depends_on:
      bdd:
        condition: service_started
    image: nginx:1.21.4
    ports:
      - "80:80"
      - "443:443"
  bdd:
    image: mongo:4.2.2
    volumes:
      - bdd:/bdd
volumes:
  bdd:
  blockchain: